language: csharp
dist: trusty
mono: none
solution: src/AzureFunction.sln
install:
- dotnet restore src/AzureFunction.sln
script:
- dotnet build src/AzureFunction.sln
- dotnet test src/AzureFunction.sln
