language: csharp
dist: trusty
mono: latest
dotnet: 2.1.400
solution: src/AzureFunction.sln
install:
- dotnet restore src/AzureFunction.sln
script:
- dotnet build src/AzureFunction.sln
- dotnet test src/AzureFunction.sln
